name: Deploy to Firebase Hosting on merge

'on':
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable' 

      - name: Replace placeholders with environment variables
        env:
          FIREBASE_CLIENT_ID: ${{ secrets.FIREBASE_CLIENT_ID }}
        run: |
          sed -i "s/{{clientId}}/$FIREBASE_CLIENT_ID/g" ./myapp/web/index.html

      - name: Build Flutter Web
        run: flutter build web
        working-directory: ./myapp

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLUTTER_6CAC9 }}'
          channelId: live
          projectId: flutter-6cac9
